# If your site is in 'https', then make sure your base url isn't written using 'http' otherwise your sitemap would
# contain http (as opposeed to https) URLs. This would affect Google indexing of your URLs.
baseURL: "https://hofbauer.tech/"
title: Lukas Hofbauer
theme: [PaperMod]

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
mainsections: ["publications", "ml-challenge", "projects", "posts"]
math: true
minify:
  disableXML: true
  # minifyOutput: true

languages:
  en:
    languageName: "English"
    weight: 1
    taxonomies:
      category: categories
      tag: tags
      series: series
    menu:
      main:
        - name: ML Challenge
          url: ml-challenge/
          weigth: 1
        - name: Projects
          url: projects/
          weigth: 2
        - name: Publications
          url: publications/
          weigth: 3
        - name: Search
          url: search/
          weight: 10
        - name: Tags
          url: tags/
          weight: 11

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  author: Lukas Hofbauer

  defaultTheme: auto
  disableThemeToggle: true
  ShowShareButtons: true
  ShareButtons: ["linkedin", "twitter"]
  ShowReadingTime: true
  # disableSpecial1stPost: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  ShowAllPagesInArchive: true
  ShowPageNums: true
  ShowToc: false

  profileMode:
    enabled: true
    title: About Me
    subtitle:
      Hi there! I'm Lukas, a cs master's student at the University of Innsbruck.
      Striving to become a AI/ML researcher.
    imageUrl: "img/headshot.jpg"
    # imageWidth: 120
    # imageHeight: 120
    buttons:
      - name: Contact Me
        url: contact
      - name: Resume
        url: resume.pdf

  socialIcons:
    - name: github
      title: Take a look at my GitHub
      url: "https://github.com/itsfernn"
    - name: twitter
      title: Follow me on Twitter
      url: "https://x.com/its_fernnn"
    - name: LinkedIn
      title: Connect with me on LinkedIn
      url: "https://www.linkedin.com/in/hofbauer-lukas/"
    - name: email
      title: Send me an email
      url: "mailto:lukas.hofbauer@student.uibk.ac.at"

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    guessSyntax: true
    noClasses: false
    # anchorLineNos: true
    codeFences: true
    # guessSyntax: true
    # lineNos: true
    style: rose-pine-dawn

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true
